# -*- coding: utf-8 -*-
"""Mediaaluno.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nwizgOuDWxs47L36enTcuDI9qxGBqIiJ
"""

n1=float(input('primeira nota do aluno:'))
n2=float(input('segunda nota do aluno:'))
n3=float(input('terceira nota do aluno:'))
media=(n1+n2+n3)/3
if media >= 7:
    print('o aluno está aprovado')
elif media >= 4:
    print('o aluno está na final')
else:
    print('o aluno está ')